public/views/admin/addMerch.html, public/views/admin/viewRequests.html, public/views/merchant/profile.html
=> Chore: Reposition Geo Inputs

public/css/merchant-portal.css, public/js/adminapp/adminApp.js, public/js/app.js, public/js/merchantapp/controllers/BillingCtrl.js, public/js/merchantapp/controllers/ProfileCtrl.js, public/js/merchantapp/controllers/RewardsCtrl.js, public/js/merchantapp/merchantApp.js, public/js/shared/authapp.js, public/js/shared/controllers/AuthCtrl.js, public/js/shared/services/PaymentSrv.js, public/views/admin/index.html, public/views/merchant/billing.html, public/views/merchant/index.html, public/views/merchant/rewards.html, public/views/shared/merchantCon.html, server.js
- Use `secure_url` from cloudinary
- Use new payment method
=> Various Fixes

gulpfile.js, package-lock.json, package.json, public/css/merchant-portal.css, public/css/style.css, public/js/adminapp/adminApp.js, public/js/adminapp/adminRoutes.js, public/js/adminapp/controllers/ConfigCtrl.js, public/js/app.js, public/js/merchantapp/controllers/BillingCtrl.js, public/js/merchantapp/controllers/RewardsCtrl.js, public/js/merchantapp/merchantApp.js, public/js/shared/authapp.js, public/js/shared/controllers/AuthCtrl.js, public/js/shared/services/ConfigSrv.js, public/views/admin/base.html, public/views/admin/config.html, public/views/admin/index.html, public/views/merchant/billing.html, public/views/merchant/index.html, public/views/merchant/rewards.html, public/views/merchant/verify.html, public/views/shared/forgotPassword.html, public/views/shared/merchantCon.html, public/views/shared/requestPasswordChange.html
* Config setting
- Add trial priod toggle to admin
- Add config service to get and set trial period
* Add duration for trial period config
* Hide billing on merchant confirmation if trial period is on
* Update error message
* Update gulp
* Add moment to the merchant confirmation page
* Disable plan in billing if trial is active
* Hide analytics info in the verify page
* Hide billing until page loads in merchant confirmation page
* Remove limit on reward duration
* Various changes
=> Free trial implementation (#10)

public/js/merchantapp/directives/index.js, public/js/shared/controllers/AuthCtrl.js, public/views/admin/addMerch.html, public/views/admin/addReward.html, public/views/merchant/rewards.html
- Make reward name and description all caps
- Change gadgets to technology
=> Various Changes

public/views/shared/merchantCon.html
=> Hot Fix: Remove 15 percent

public/js/merchantapp/controllers/ProfileCtrl.js, public/js/merchantapp/controllers/RewardsCtrl.js, public/js/merchantapp/controllers/RewardsListCtrl.js, public/js/merchantapp/merchappRoutes.js, public/views/merchant/rewardsList.html
- move account confirmation to rewards list
=> Release - 10/11/2021

.env.example, .gitignore, public/js/adminapp/controllers/ConfigCtrl.js, public/js/merchantapp/controllers/AnalyticsCtrl.js, public/js/merchantapp/controllers/ProfileCtrl.js, public/js/merchantapp/controllers/RewardDetailAnalyticsCtrl.js, public/js/merchantapp/controllers/RewardsCtrl.js, public/js/shared/controllers/AuthCtrl.js
=> Fix: Reward Upload

public/views/admin/index.html, public/views/merchant/index.html, public/views/shared/forgotPassword.html, public/views/shared/merchantCon.html, public/views/shared/requestPasswordChange.html
=> Feature: Add Theme

public/js/merchantapp/merchappRoutes.js, public/views/merchant/analytics.html, public/views/merchant/verify.html
- Hide Analytics
- Show Delivery Stats
=> Feature: Hide Analytics and Show Delivery Stats

public/js/shared/controllers/AuthCtrl.js
=> Release: Default Query

public/js/adminapp/controllers/MerchantCtrl.js, public/js/adminapp/controllers/RewardsCtrl.js, public/js/adminapp/services/RewardsSrv.js, public/js/merchantapp/services/MerchantSrv.js, public/views/admin/viewMerch.html, public/views/admin/viewRewards.html
=> Enhancement: Improve admin experience.

public/js/adminapp/adminApp.js, public/js/merchantapp/merchantApp.js
=> Fix: Token Expiration not Redirecting

.gitignore, public/js/adminapp/controllers/MerchantCtrl.js, public/js/config.js, public/js/merchantapp/services/MerchantSrv.js, public/views/admin/login.html, public/views/admin/viewMerch.html
=> closes #75 | Activate/Deactivate Merchant 

public/js/adminapp/controllers/RewardsCtrl.js, public/js/adminapp/services/RewardsSrv.js, public/views/admin/viewMerch.html, public/views/admin/viewRewards.html
=> closes #75 | Hide/Unhide Rewards 

public/js/adminapp/controllers/RequestCtrl.js, public/js/adminapp/services/AdminSrv.js, public/views/admin/base.html, public/views/admin/viewRequests.html
- Allows admins send general notifications to customers.
=> Feature: General Notifications

public/css/merchant-portal.css, public/css/table.css, public/js/merchantapp/controllers/RewardsCtrl.js, public/js/shared/services/RewardsSrv.js, public/views/merchant/login.html, public/views/merchant/rewards.html
=> Closes #97 | toggle expired deals

public/js/adminapp/adminApp.js, public/js/adminapp/controllers/RequestCtrl.js, public/js/shared/services/CoupinSrv.js, public/views/admin/viewRequests.html
=> Feat: Admin Cancel Orders

public/css/merchant-portal.css, public/js/merchantapp/controllers/ProfileCtrl.js, public/js/shared/controllers/AuthCtrl.js, public/views/merchant/login.html, public/views/merchant/profile.html
=> Feat: Add referral Code for Merchant 

public/js/adminapp/controllers/CustomerCtrl.js, public/js/adminapp/services/CustomerSrv.js, public/views/admin/viewCustomers.html
=> Feature: download customer report

public/css/table.css, public/js/adminapp/controllers/AddMerchantCtrl.js, public/js/merchantapp/controllers/HomeCtrl.js, public/views/merchant/verify.html
=> add selectable feature to coupins

public/css/table.css, public/views/merchant/verify.html
=> Enhancement: Change Theme of checkbox

public/js/adminapp/controllers/RequestCtrl.js, public/js/adminapp/services/RequestSrv.js, public/views/admin/viewRequests.html
=> add pagination

public/js/adminapp/controllers/RewardsCtrl.js, public/js/config.js
=> admin: sort merchants dropdown
